site_name: 자유 커뮤니티 위키 
site_url: https://freecommunity.kro.kr

theme:
  name: material
  language: ko
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    tag:
      dev: fontawesome/solid/code
      edit: material/pencil
      view: material/eye
  custom_dir: overrides
  features:
    - search.suggest
    - search.share
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  palette:
    primary: deep purple
plugins:
  - search
  - blog
  - tags
  - git-revision-date-localized:
      type: datetime
  - git-committers:
      repository: opcweb/FreeCommunitywiki
      branch: main

nav:
  - index.md
  - 자유 커뮤니티 정신:
    - spirit/index.md
  - 검열 저항:
    - censorship/index.md
    - censorship/pgp.md
  - 블로그:
    - blog/index.md

extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opcweb/FreeCommunityWiki
    - icon: fontawesome/brands/kakao-talk
      link: https://open.kakao.com/o/gxgb8LPe
  tags:
      개발: dev
  consent:
    title: 자유인 확인
    description: >- 
      당신이 동의 버튼을 클릭한 경우, 당신은 자신이 노무현 밈을 사랑한다는 것에 동의하는 것으로 간주됩니다. 또한 쿠키 사용에 동의하는 것으로 간주되며, 관리 버튼을 클릭하여 쿠키 설정을 변경할 수 있습니다.
    actions:
    - accept
    - manage
  generator: false
  analytics:
    provider: google
    tracking_id: G-749JF2PMC2

markdown_extensions: 
  - md_in_html
  - footnotes
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: >- 
  <img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-sa.svg" alt="CC BY-NC-SA" width="60"><br>Copyright &copy; 2025 <a href="https://github.com/opcweb">opcweb</a> All Rights Reserved. 특별히 명시되어있지 않은 경우, 이 사이트 내의 모든 저작물은 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ko">CC BY-NC-SA 라이선스</a>로 보호됩니다.

repo_url: https://github.com/opcweb/FreeCommunityWiki
repo_name: FreeCommunityWiki
edit_uri: edit/main/docs/